export const ADJECTIVES = [
  "aoi", "akai", "shiroi", "kuroi", "kiiroi", "chairoi", "shizuka", "hayai",
  "nagai", "mijikai", "atarashii", "kashikoi", "ookii", "chiisai", "takai", "hiroi",
  "suzushii", "atatakai", "tsumetai", "akarui", "tsuyoi", "karui", "katai", "yawarakai",
  "amai", "karai", "nigai", "suppai", "shibui", "oishii", "tanoshii", "ureshii",
  "yasashii", "utsukushii", "kawaii", "kirei", "genki", "shinsetsu", "majime", "nigiyaka",
  "odayaka", "sawayaka", "hanayaka", "nodoka", "yutaka", "tashika", "kenmei", "yuukan",
  "sunao", "shoujiki", "teinei", "jouzu", "tokui", "yuumei", "daiji", "taisetsu",
  "benri", "kantan", "fushigi", "subarashii", "mezurashii", "natsukashii", "isogashii", "mabushii",
  "kuwashii", "tadashii", "sugoi", "erai", "wakai", "marui", "shikakui", "hosoi",
  "futoi", "fukai", "tooi", "chikai", "surudoi", "kiyoi", "tootoi", "isamashii",
  "takumashii", "yukai", "kaiteki", "heiwa", "jiyuu", "anzen", "kenkou", "shinsen",
  "junsui", "toumei", "kaikatsu", "youki", "nonki", "kigaru", "migaru", "kiyoraka",
  "nameraka", "karoyaka", "shinayaka", "sukoyaka", "hogaraka", "ooraka", "nagoyaka", "shitoyaka",
  "azayaka", "komayaka", "sumiyaka", "yuruyaka", "taira", "massugu", "atsui", "samui",
];

export const NOUNS = [
  "kitsune", "tanuki", "tsuru", "kame", "sakura", "kawa", "yama", "tsuki",
  "hoshi", "sora", "umi", "mori", "hana", "kaze", "ame", "yuki",
  "kumo", "niji", "taki", "ike", "mizuumi", "shima", "hama", "nami",
  "iwa", "ishi", "suna", "tani", "oka", "hayashi", "take", "matsu",
  "ume", "momo", "kaede", "sugi", "yanagi", "fuji", "tsubaki", "ayame",
  "kiku", "yuri", "botan", "asagao", "himawari", "tanpopo", "sumire", "inu",
  "neko", "usagi", "shika", "kuma", "saru", "tora", "uma", "ushi",
  "hitsuji", "risu", "nezumi", "kujira", "iruka", "tako", "ika", "kani",
  "ebi", "sakana", "koi", "kingyo", "tori", "suzume", "karasu", "hato",
  "taka", "washi", "fukurou", "tsubame", "uguisu", "kamome", "hakuchou", "tonbo",
  "chou", "hotaru", "semi", "kaeru", "tokage", "mikan", "ringo", "kaki",
  "nashi", "budou", "ichigo", "kuri", "mame", "kome", "mugi", "ocha",
  "mochi", "dango", "sushi", "soba", "udon", "tofu", "nori", "fude",
  "kami", "hon", "tsukue", "isu", "mado", "tobira", "kagi", "kasa",
  "kutsu", "boushi", "tokei", "kagami", "fune", "hashi", "michi", "machi",
  "mura", "shiro", "tera", "niwa", "mizu", "tsuchi", "kaminari", "arashi",
  "kiri", "asa", "hiru", "yoru", "yuugata", "haru", "natsu", "aki", "fuyu",
];
